version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install packages
          command: make install-test
      - run:
          name: Run tests
          command: python -m pytest --cov=protowhat
  publish:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          command: |
            python setup.py sdist bdist_wheel
            pip install pipenv
            pipenv install twine
            pipenv run twine upload --verbose --repository pypi dist/*
workflows:
  build:
    jobs:
      - build-and-test
      - publish:
          requires:
            - build-and-test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
